# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3.7'

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    image: csci652:latest
    container_name: server
    working_dir: /csci652/project1
    networks:
      - csci652network
    ports:
      - 9091
      - 9092
      - 9093
    command:
      - /bin/bash
      - -c
      - java -Xmx2048m -cp target/project1-1.0-SNAPSHOT.jar edu.rit.cs.TCPServer
      - |
        echo "Initialize peer1...done!"
        tail -f /dev/null


  peer2:
    image: csci652:latest
    container_name: client
    depends_on:
      - peer1
    working_dir: /csci652/project1 
    networks:
      - csci652network
    ports:
      - 9091
      - 9092
      - 9093
    command:
      - /bin/bash
      - -c
      - java -Xmx2048m -cp  target/project1-1.0-SNAPSHOT.jar edu.rit.cs.TCPClient affr.csv peer1
      - |
        echo "Initialize peer2...done!"
        tail -f /dev/null

  rmiserver:
    image: csci652:latest
    container_name: rmiserver
    depends_on:
      - peer1
    working_dir: /csci652/project2
    networks:
      - csci652network
    ports:
      - 1099
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize rmiserver...done!"
        tail -f /dev/null

  rmiclient:
    image: csci652:latest
    container_name: rmiclient
    depends_on:
      - rmiserver
    working_dir: /csci652/project2
    networks:
    - csci652network
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize rmiclient...done!"
        tail -f /dev/null



networks:
  csci652network: